import type { PlannedTrip } from '@/engine/types';
import type { TripBrief } from '@/lib/schemas';
import { db } from '../db';
import {
  CONFIDENCE_TO_DB,
  SOURCE_KIND_TO_DB,
  asJson,
  budgetLineRows,
  fromDbDate,
  itineraryDayRow,
  itineraryItemRows,
  lodgingOptionRow,
  preferenceFromBrief,
  snapshotFor,
  taskRowsFor,
  transportOptionRow,
  travellersFromBrief,
  tripHeaderFromBrief,
} from './mapping';

/**
 * Trip persistence.
 *
 * All writes for a plan happen in a single transaction. A half-written trip —
 * days without items, a budget without lines — would be worse than no trip at
 * all, because the dashboard would render it as though it were complete.
 *
 * Ownership is enforced in every read and write by including `userId` in the
 * where clause rather than fetching and then comparing. A trip id in a URL is
 * a claim, not an authorisation.
 */

export interface CreateTripInput {
  userId: string;
  brief: TripBrief;
  title?: string;
}

/** Create a DRAFT trip from a brief, before any planning has run. */
export async function createTrip(input: CreateTripInput) {
  const header = tripHeaderFromBrief(input.brief, input.title);

  return db().trip.create({
    data: {
      ...header,
      userId: input.userId,
      // Set directly rather than by a follow-up update: over a remote
      // connection every avoided query is a visible fraction of a second.
      status: 'PLANNING',
      preference: { create: preferenceFromBrief(input.brief) },
      travellers: { create: travellersFromBrief(input.brief) },
    },
    include: { preference: true, travellers: true },
  });
}

/**
 * Store a finished plan against an existing trip.
 *
 * Replaces any previous itinerary rather than appending: a trip has exactly
 * one current plan, and the previous one is preserved as a TripVersion
 * snapshot rather than as orphaned rows.
 */
export async function savePlan(tripId: string, userId: string, plan: PlannedTrip) {
  return db().$transaction(
    async (tx) => {
      const trip = await tx.trip.findFirst({ where: { id: tripId, userId, deletedAt: null } });
      if (!trip) return null;

      // Clear the previous current plan. Cascades remove itinerary items.
      //
      // Skipped entirely on a first save: a trip that has never been planned
      // has nothing to clear, and five DELETEs that match nothing still cost
      // five round trips — over a second on a remote database.
      if (trip.currentVersionId !== null) {
        await tx.itineraryDay.deleteMany({ where: { tripId } });
        await tx.transportOption.deleteMany({ where: { tripId } });
        await tx.lodgingOption.deleteMany({ where: { tripId } });
        await tx.budgetLine.deleteMany({ where: { tripId } });
        await tx.tripTask.deleteMany({ where: { tripId, autoGenerated: true } });
      }

      const nextVersionNo =
        trip.currentVersionId === null
          ? 1
          : ((
              await tx.tripVersion.aggregate({
                where: { tripId },
                _max: { versionNo: true },
              })
            )._max.versionNo ?? 0) + 1;

      const version = await tx.tripVersion.create({
        data: {
          tripId,
          versionNo: nextVersionNo,
          reason: nextVersionNo === 1 ? 'initial plan' : 'replanned',
          engineMs: Object.values(plan.timings).reduce<number>((s, ms) => s + (ms ?? 0), 0),
          stageTimingMs: asJson(plan.timings),
          snapshot: asJson(snapshotFor(plan)),
        },
      });

      await tx.validationReport.create({
        data: {
          tripVersionId: version.id,
          violations: asJson(plan.validation.violations),
          hardCount: plan.validation.hardCount,
          softCount: plan.validation.softCount,
          relaxedConstraints: plan.relaxedConstraints,
        },
      });

      // --- options, selected ones flagged -------------------------------------
      const selectedTransportIds = new Set([
        plan.selections.outbound.id,
        plan.selections.inbound.id,
      ]);
      const transportRows = dedupeById([
        plan.selections.outbound,
        plan.selections.inbound,
        ...plan.selections.alternatives.transport,
      ]).map((option) => ({
        ...transportOptionRow(option, selectedTransportIds.has(option.id)),
        tripId,
      }));
      await tx.transportOption.createMany({ data: transportRows });

      const lodgingRows = dedupeById([
        plan.selections.lodging,
        ...plan.selections.alternatives.lodging,
      ]).map((option) => ({
        ...lodgingOptionRow(option, option.id === plan.selections.lodging.id),
        tripId,
      }));
      await tx.lodgingOption.createMany({ data: lodgingRows });

      // --- POI cache, shared across every user's trips -------------------------
      //
      // Insert-if-absent then read back, rather than upserting each POI in turn.
      // A shortlist runs to twenty-odd places, and twenty sequential upserts over
      // a remote connection is several seconds of pure round-trip latency — which
      // is what previously blew the transaction timeout.
      //
      // Refreshing an existing row's mutable facts is deliberately dropped here:
      // it is a cache-freshness nicety, not a correctness requirement, and it is
      // not worth a query per POI on every save.
      await tx.poi.createMany({
        data: plan.selections.shortlist.map((poi) => ({
          providerRef: poi.providerRef,
          name: poi.name,
          category: poi.category,
          lat: poi.geo.lat,
          lng: poi.geo.lng,
          rating: poi.rating ?? null,
          reviewCount: poi.reviewCount ?? null,
          priceLevel: poi.priceLevel ?? null,
          typicalDurationMins: poi.typicalDurationMins,
          openingHours: asJson(poi.openingHours),
          address: poi.address ?? null,
          mapsUrl: poi.mapsUrl ?? null,
          websiteUrl: poi.websiteUrl ?? null,
          tags: poi.tags,
          provider: poi.provenance.provider,
          sourceKind: SOURCE_KIND_TO_DB[poi.provenance.sourceKind],
          confidence: CONFIDENCE_TO_DB[poi.provenance.confidence],
          lastFetchedAt: new Date(poi.provenance.fetchedAt),
        })),
        skipDuplicates: true,
      });

      const poiRows = await tx.poi.findMany({
        where: { providerRef: { in: plan.selections.shortlist.map((p) => p.providerRef) } },
        select: { id: true, providerRef: true },
      });
      const dbIdByProviderRef = new Map(poiRows.map((row) => [row.providerRef, row.id]));
      const poiIdByDomainId = new Map<string, string>();
      for (const poi of plan.selections.shortlist) {
        const dbId = dbIdByProviderRef.get(poi.providerRef);
        if (dbId) poiIdByDomainId.set(poi.id, dbId);
      }

      // --- itinerary -----------------------------------------------------------
      // Days first, then every item in one insert, rather than a nested create
      // per day.
      await tx.itineraryDay.createMany({
        data: plan.days.map((day) => ({ ...itineraryDayRow(day), tripId })),
      });

      const dayRows = await tx.itineraryDay.findMany({
        where: { tripId },
        select: { id: true, dayIndex: true },
      });
      const dayIdByIndex = new Map(dayRows.map((row) => [row.dayIndex, row.id]));

      const itemRows = plan.days.flatMap((day) => {
        const dayId = dayIdByIndex.get(day.dayIndex);
        if (!dayId) return [];
        return itineraryItemRows(day, poiIdByDomainId).map((item) => ({ ...item, dayId }));
      });
      if (itemRows.length > 0) {
        await tx.itineraryItem.createMany({ data: itemRows });
      }

      await tx.budgetLine.createMany({
        data: budgetLineRows(plan.budget).map((line) => ({ ...line, tripId })),
      });

      await tx.tripTask.createMany({
        data: taskRowsFor(plan).map((task) => ({
          ...task,
          kind: task.kind as 'BOOKING',
          tripId,
        })),
      });

      return tx.trip.update({
        where: { id: tripId },
        data: {
          status: plan.validation.hardCount > 0 ? 'DRAFT_INVALID' : 'PLANNED',
          currentVersionId: version.id,
        },
      });
    },
    {
      // Headroom over a remote connection. The batching above keeps a typical
      // save well inside this; the allowance is for a cold Neon instance
      // waking up, not for the query count.
      timeout: 20_000,
      maxWait: 10_000,
    },
  );
}

/** Keep the first occurrence of each id, preserving order. */
function dedupeById<T extends { id: string }>(items: readonly T[]): T[] {
  const seen = new Set<string>();
  return items.filter((item) => {
    if (seen.has(item.id)) return false;
    seen.add(item.id);
    return true;
  });
}

/** A user's trips, split into upcoming and past by end date. */
export async function listTrips(userId: string) {
  const trips = await db().trip.findMany({
    where: { userId, deletedAt: null },
    orderBy: { startDate: 'asc' },
    include: {
      budgetLines: true,
      _count: { select: { days: true } },
    },
  });

  const today = new Date();
  today.setUTCHours(0, 0, 0, 0);

  const shape = (trip: (typeof trips)[number]) => ({
    id: trip.id,
    title: trip.title,
    destinationCity: trip.destinationCity,
    startDate: fromDbDate(trip.startDate),
    endDate: fromDbDate(trip.endDate),
    travellerCount: trip.travellerCount,
    budgetTotalMinor: trip.budgetTotalMinor,
    estimatedMinor: trip.budgetLines.reduce((sum, line) => sum + line.estimatedMinor, 0),
    currency: trip.currency,
    status: trip.status,
    dayCount: trip._count.days,
  });

  return {
    upcoming: trips.filter((t) => t.endDate >= today).map(shape),
    past: trips
      .filter((t) => t.endDate < today)
      .reverse()
      .map(shape),
  };
}

/** One trip with everything the dashboard needs. Null when not the user's. */
export async function getTrip(tripId: string, userId: string) {
  // Every `include` is another round trip, and at ~300 ms each that is the
  // difference between a page that feels instant and one that feels broken.
  // Loaded here is exactly what the trip page renders — `preference`,
  // `travellers` and each item's full `poi` row are deliberately absent
  // because nothing displays them yet. Add them back with the screen that
  // needs them, not before.
  return db().trip.findFirst({
    where: { id: tripId, userId, deletedAt: null },
    include: {
      transportOpts: { orderBy: { pricePerPersonMinor: 'asc' } },
      lodgingOpts: { orderBy: { nightlyRateMinor: 'asc' } },
      budgetLines: true,
      tasks: { orderBy: { seq: 'asc' } },
      days: {
        orderBy: { dayIndex: 'asc' },
        include: { items: { orderBy: { seq: 'asc' } } },
      },
      currentVersion: { include: { validation: true } },
    },
  });
}

/** Soft delete, so a mis-click is recoverable. */
export async function deleteTrip(tripId: string, userId: string) {
  const result = await db().trip.updateMany({
    where: { id: tripId, userId, deletedAt: null },
    data: { deletedAt: new Date() },
  });
  return result.count > 0;
}

export async function setTripStatus(
  tripId: string,
  userId: string,
  status: 'PLANNING' | 'PLANNED' | 'DRAFT_INVALID',
) {
  const result = await db().trip.updateMany({
    where: { id: tripId, userId, deletedAt: null },
    data: { status },
  });
  return result.count > 0;
}
