import type { PlannedTrip } from '@/engine/types';
import type { TripBrief } from '@/lib/schemas';
import { db } from '../db';
import {
  asJson,
  budgetLineRows,
  fromDbDate,
  itineraryDayRow,
  itineraryItemRows,
  lodgingOptionRow,
  preferenceFromBrief,
  snapshotFor,
  taskRowsFor,
  transportOptionRow,
  travellersFromBrief,
  tripHeaderFromBrief,
} from './mapping';

/**
 * Trip persistence.
 *
 * All writes for a plan happen in a single transaction. A half-written trip —
 * days without items, a budget without lines — would be worse than no trip at
 * all, because the dashboard would render it as though it were complete.
 *
 * Ownership is enforced in every read and write by including `userId` in the
 * where clause rather than fetching and then comparing. A trip id in a URL is
 * a claim, not an authorisation.
 */

export interface CreateTripInput {
  userId: string;
  brief: TripBrief;
  title?: string;
}

/** Create a DRAFT trip from a brief, before any planning has run. */
export async function createTrip(input: CreateTripInput) {
  const header = tripHeaderFromBrief(input.brief, input.title);

  return db().trip.create({
    data: {
      ...header,
      userId: input.userId,
      status: 'DRAFT',
      preference: { create: preferenceFromBrief(input.brief) },
      travellers: { create: travellersFromBrief(input.brief) },
    },
    include: { preference: true, travellers: true },
  });
}

/**
 * Store a finished plan against an existing trip.
 *
 * Replaces any previous itinerary rather than appending: a trip has exactly
 * one current plan, and the previous one is preserved as a TripVersion
 * snapshot rather than as orphaned rows.
 */
export async function savePlan(tripId: string, userId: string, plan: PlannedTrip) {
  return db().$transaction(async (tx) => {
    const trip = await tx.trip.findFirst({ where: { id: tripId, userId, deletedAt: null } });
    if (!trip) return null;

    // Clear the previous current plan. Cascades remove itinerary items.
    await tx.itineraryDay.deleteMany({ where: { tripId } });
    await tx.transportOption.deleteMany({ where: { tripId } });
    await tx.lodgingOption.deleteMany({ where: { tripId } });
    await tx.budgetLine.deleteMany({ where: { tripId } });
    await tx.tripTask.deleteMany({ where: { tripId, autoGenerated: true } });

    const nextVersionNo =
      ((
        await tx.tripVersion.aggregate({
          where: { tripId },
          _max: { versionNo: true },
        })
      )._max.versionNo ?? 0) + 1;

    const version = await tx.tripVersion.create({
      data: {
        tripId,
        versionNo: nextVersionNo,
        reason: nextVersionNo === 1 ? 'initial plan' : 'replanned',
        engineMs: Object.values(plan.timings).reduce<number>((s, ms) => s + (ms ?? 0), 0),
        stageTimingMs: asJson(plan.timings),
        snapshot: asJson(snapshotFor(plan)),
      },
    });

    await tx.validationReport.create({
      data: {
        tripVersionId: version.id,
        violations: asJson(plan.validation.violations),
        hardCount: plan.validation.hardCount,
        softCount: plan.validation.softCount,
        relaxedConstraints: plan.relaxedConstraints,
      },
    });

    // --- options, selected ones flagged -------------------------------------
    const selectedTransportRefs = new Set([
      plan.selections.outbound.id,
      plan.selections.inbound.id,
    ]);
    const transportOptions = [
      plan.selections.outbound,
      plan.selections.inbound,
      ...plan.selections.alternatives.transport,
    ];
    const seenTransport = new Set<string>();
    for (const option of transportOptions) {
      if (seenTransport.has(option.id)) continue;
      seenTransport.add(option.id);
      await tx.transportOption.create({
        data: { ...transportOptionRow(option, selectedTransportRefs.has(option.id)), tripId },
      });
    }

    const lodgingOptions = [plan.selections.lodging, ...plan.selections.alternatives.lodging];
    const seenLodging = new Set<string>();
    for (const option of lodgingOptions) {
      if (seenLodging.has(option.id)) continue;
      seenLodging.add(option.id);
      await tx.lodgingOption.create({
        data: {
          ...lodgingOptionRow(option, option.id === plan.selections.lodging.id),
          tripId,
        },
      });
    }

    // --- POI cache, shared across every user's trips -------------------------
    const poiIdByDomainId = new Map<string, string>();
    for (const poi of plan.selections.shortlist) {
      const row = await tx.poi.upsert({
        where: { providerRef: poi.providerRef },
        create: {
          providerRef: poi.providerRef,
          name: poi.name,
          category: poi.category,
          lat: poi.geo.lat,
          lng: poi.geo.lng,
          rating: poi.rating ?? null,
          reviewCount: poi.reviewCount ?? null,
          priceLevel: poi.priceLevel ?? null,
          typicalDurationMins: poi.typicalDurationMins,
          openingHours: asJson(poi.openingHours),
          address: poi.address ?? null,
          mapsUrl: poi.mapsUrl ?? null,
          websiteUrl: poi.websiteUrl ?? null,
          tags: poi.tags,
          provider: poi.provenance.provider,
          sourceKind: poi.provenance.sourceKind.toUpperCase() as 'MOCK',
          confidence: poi.provenance.confidence.toUpperCase() as 'MEDIUM',
          lastFetchedAt: new Date(poi.provenance.fetchedAt),
        },
        // Refresh the mutable facts; identity and id stay put.
        update: {
          name: poi.name,
          rating: poi.rating ?? null,
          openingHours: asJson(poi.openingHours),
          lastFetchedAt: new Date(poi.provenance.fetchedAt),
        },
      });
      poiIdByDomainId.set(poi.id, row.id);
    }

    // --- itinerary -----------------------------------------------------------
    for (const day of plan.days) {
      await tx.itineraryDay.create({
        data: {
          ...itineraryDayRow(day),
          tripId,
          items: { create: itineraryItemRows(day, poiIdByDomainId) },
        },
      });
    }

    await tx.budgetLine.createMany({
      data: budgetLineRows(plan.budget).map((line) => ({ ...line, tripId })),
    });

    await tx.tripTask.createMany({
      data: taskRowsFor(plan).map((task) => ({
        ...task,
        kind: task.kind as 'BOOKING',
        tripId,
      })),
    });

    return tx.trip.update({
      where: { id: tripId },
      data: {
        status: plan.validation.hardCount > 0 ? 'DRAFT_INVALID' : 'PLANNED',
        currentVersionId: version.id,
      },
    });
  });
}

/** A user's trips, split into upcoming and past by end date. */
export async function listTrips(userId: string) {
  const trips = await db().trip.findMany({
    where: { userId, deletedAt: null },
    orderBy: { startDate: 'asc' },
    include: {
      budgetLines: true,
      _count: { select: { days: true } },
    },
  });

  const today = new Date();
  today.setUTCHours(0, 0, 0, 0);

  const shape = (trip: (typeof trips)[number]) => ({
    id: trip.id,
    title: trip.title,
    destinationCity: trip.destinationCity,
    startDate: fromDbDate(trip.startDate),
    endDate: fromDbDate(trip.endDate),
    travellerCount: trip.travellerCount,
    budgetTotalMinor: trip.budgetTotalMinor,
    estimatedMinor: trip.budgetLines.reduce((sum, line) => sum + line.estimatedMinor, 0),
    currency: trip.currency,
    status: trip.status,
    dayCount: trip._count.days,
  });

  return {
    upcoming: trips.filter((t) => t.endDate >= today).map(shape),
    past: trips
      .filter((t) => t.endDate < today)
      .reverse()
      .map(shape),
  };
}

/** One trip with everything the dashboard needs. Null when not the user's. */
export async function getTrip(tripId: string, userId: string) {
  return db().trip.findFirst({
    where: { id: tripId, userId, deletedAt: null },
    include: {
      preference: true,
      travellers: true,
      transportOpts: { orderBy: { pricePerPersonMinor: 'asc' } },
      lodgingOpts: { orderBy: { nightlyRateMinor: 'asc' } },
      budgetLines: true,
      tasks: { orderBy: { seq: 'asc' } },
      days: {
        orderBy: { dayIndex: 'asc' },
        include: { items: { orderBy: { seq: 'asc' }, include: { poi: true } } },
      },
      currentVersion: { include: { validation: true } },
    },
  });
}

/** Soft delete, so a mis-click is recoverable. */
export async function deleteTrip(tripId: string, userId: string) {
  const result = await db().trip.updateMany({
    where: { id: tripId, userId, deletedAt: null },
    data: { deletedAt: new Date() },
  });
  return result.count > 0;
}

export async function setTripStatus(
  tripId: string,
  userId: string,
  status: 'PLANNING' | 'PLANNED' | 'DRAFT_INVALID',
) {
  const result = await db().trip.updateMany({
    where: { id: tripId, userId, deletedAt: null },
    data: { status },
  });
  return result.count > 0;
}
